"""empty message

Revision ID: 9e64c6f1650d
Revises: a5828517e403
Create Date: 2019-07-03 13:50:30.060297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e64c6f1650d'
down_revision = 'a5828517e403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'quantity')
    # ### end Alembic commands ###
