"""empty message

Revision ID: b9e0ec4e92f1
Revises: 95d074ed31d2
Create Date: 2019-07-02 22:49:17.366173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e0ec4e92f1'
down_revision = '95d074ed31d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('body', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'body')
    # ### end Alembic commands ###
