"""empty message

Revision ID: c7ab82e1d7f9
Revises: b9e0ec4e92f1
Create Date: 2019-07-02 22:50:44.290348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ab82e1d7f9'
down_revision = 'b9e0ec4e92f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('eventname', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'events', ['eventname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_column('events', 'eventname')
    # ### end Alembic commands ###
