"""empty message

Revision ID: eeb957f7aa45
Revises: 9c691f63082d
Create Date: 2019-07-04 20:03:19.288227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb957f7aa45'
down_revision = '9c691f63082d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rateevent',
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('rate_event', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_event'], ['events.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('rater_id', 'rate_event')
    )
    op.drop_constraint('events_user_rate_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'user_rate_id')
    op.drop_column('events', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('user_rate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_user_rate_id_fkey', 'events', 'users', ['user_rate_id'], ['id'])
    op.drop_table('rateevent')
    # ### end Alembic commands ###
