"""empty message

Revision ID: 09b83471090c
Revises: 5b24ff894e88
Create Date: 2019-07-08 15:06:57.339311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b83471090c'
down_revision = '5b24ff894e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'hide',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'hide',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
