"""empty message

Revision ID: 102e7137eeae
Revises: e0764c17d254
Create Date: 2019-07-02 14:47:54.042419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102e7137eeae'
down_revision = 'e0764c17d254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate',
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('rater_id', 'target_user_id')
    )
    op.drop_table('rating_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_users',
    sa.Column('rater_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name='rating_users_rater_id_fkey'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name='rating_users_target_user_id_fkey'),
    sa.PrimaryKeyConstraint('rater_id', 'target_user_id', name='rating_users_pkey')
    )
    op.drop_table('rate')
    # ### end Alembic commands ###
