"""empty message

Revision ID: 2432adb9c057
Revises: c7ab82e1d7f9
Create Date: 2019-07-03 00:24:02.461233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2432adb9c057'
down_revision = 'c7ab82e1d7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_url')
    # ### end Alembic commands ###
