"""empty message

Revision ID: 3699fe1adf4b
Revises: b754dae4e4e9
Create Date: 2019-07-08 10:18:04.170825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3699fe1adf4b'
down_revision = 'b754dae4e4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'body',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('events', 'image_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'image_url',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('events', 'body',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
