"""empty message

Revision ID: 4fb5dfdd8f23
Revises: 9e64c6f1650d
Create Date: 2019-07-03 14:26:20.048646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb5dfdd8f23'
down_revision = '9e64c6f1650d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('totalbill', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'totalbill')
    # ### end Alembic commands ###
