"""empty message

Revision ID: 549d446e8f15
Revises: 4fb5dfdd8f23
Create Date: 2019-07-04 13:16:22.496964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549d446e8f15'
down_revision = '4fb5dfdd8f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rate', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rate', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
