"""empty message

Revision ID: 5b24ff894e88
Revises: 9127d2e632ce
Create Date: 2019-07-08 14:53:03.635866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b24ff894e88'
down_revision = '9127d2e632ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hide', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'hide')
    # ### end Alembic commands ###
