"""empty message

Revision ID: 9127d2e632ce
Revises: 3699fe1adf4b
Create Date: 2019-07-08 11:11:05.020283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9127d2e632ce'
down_revision = '3699fe1adf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'rating')
    # ### end Alembic commands ###
