"""empty message

Revision ID: 9c691f63082d
Revises: 549d446e8f15
Create Date: 2019-07-04 19:34:28.246777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c691f63082d'
down_revision = '549d446e8f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('user_rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['user_rate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'user_rate_id')
    op.drop_column('events', 'rating')
    # ### end Alembic commands ###
