"""empty message

Revision ID: a5828517e403
Revises: 109d907273b3
Create Date: 2019-07-03 13:25:39.322849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5828517e403'
down_revision = '109d907273b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'users', ['buyer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'buyer_id')
    # ### end Alembic commands ###
