"""empty message

Revision ID: b754dae4e4e9
Revises: a6bde3e8b49b
Create Date: 2019-07-06 09:00:53.901019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b754dae4e4e9'
down_revision = 'a6bde3e8b49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('avatar_url', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'avatar_url')
    # ### end Alembic commands ###
