"""empty message

Revision ID: c57afdc3817c
Revises: d7828ba33e83
Create Date: 2019-07-02 12:09:03.492380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57afdc3817c'
down_revision = 'd7828ba33e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate',
    sa.Column('rater_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], )
    )
    op.add_column('profile_user', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('profile_user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('profile_user', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('profile_user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('profile_user_email_key', 'profile_user', type_='unique')
    op.drop_column('profile_user', 'name')
    op.drop_column('profile_user', 'password')
    op.drop_column('profile_user', 'email')
    op.add_column('users', sa.Column('rating_star', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating_star')
    op.add_column('profile_user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('profile_user', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('profile_user', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('profile_user_email_key', 'profile_user', ['email'])
    op.drop_column('profile_user', 'updated_at')
    op.drop_column('profile_user', 'phone')
    op.drop_column('profile_user', 'created_at')
    op.drop_column('profile_user', 'address')
    op.drop_table('rate')
    # ### end Alembic commands ###
