"""empty message

Revision ID: c9164a303f2e
Revises: df41a3a8a80c
Create Date: 2019-07-09 10:08:02.249879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9164a303f2e'
down_revision = 'df41a3a8a80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genremovie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_genre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_genre'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genremovie')
    op.drop_table('genre')
    # ### end Alembic commands ###
