"""empty message

Revision ID: e0764c17d254
Revises: 9b018c42ad5e
Create Date: 2019-07-02 14:23:45.559990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0764c17d254'
down_revision = '9b018c42ad5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_users',
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('rater_id', 'target_user_id')
    )
    op.drop_table('rate')
    op.drop_column('users', 'rating_star')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating_star', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('rate',
    sa.Column('rater_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name='rate_rater_id_fkey'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name='rate_target_user_id_fkey')
    )
    op.drop_table('rating_users')
    # ### end Alembic commands ###
