"""empty message

Revision ID: e6b59996dfee
Revises: 09b83471090c
Create Date: 2019-07-08 16:09:09.425238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b59996dfee'
down_revision = '09b83471090c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('events', sa.Column('stock', sa.Integer(), nullable=False))
    # op.alter_column('events', 'hide',
    #            existing_type=sa.BOOLEAN(),
    #            type_=sa.String(length=10),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('events', 'hide',
    #            existing_type=sa.String(length=10),
    #            type_=sa.BOOLEAN(),
    #            existing_nullable=True)
    # op.drop_column('events', 'stock')
    # ### end Alembic commands ###
    pass
